ProyectoIntegrador2018/i2t2-campe

app/channels/application_cable/channel.rb

prueba commit

---

.gitignore
Gemfile
Gemfile.lock
config/database.yml
db/schema.rb
development-entrypoint
docker-compose.yml
dockerfile

Docker configuration

---

db/migrate/20191007214453_add_columns_to_users.rb
db/migrate/20191007214919_add_column_to_admin.rb
db/schema.rb

Completes Users and admins models

Updtaes Admins Users models

---

app/controllers/users_controller.rb
app/views/pages/home.html.erb
app/views/users/index.html.erb
config/routes.rb

Agregar template de tabla de usuarios, poner registro usuarios para admins y agregar boton para ver la tabla de usuarios.

Agregar template de tabla de usuarios

---

app/controllers/users_controller.rb
app/views/users/index.html.erb

Delets user

---

.codeclimate.yml
db/seeds.rb

Actualizar las seeds y agregar archivo de configuracion de codeclimate para que ignore los archivos generados por materialize

add codeclimate exception to materialize files and update seeds

---

app/controllers/admins/registrations_controller.rb
app/views/devise/registrations/new.html.erb
app/views/pages/index.html.erb
app/views/users/index.html.erb

Agregar botón de registrar admins y override del registration controller del admin para que un admin logged in pueda entrar a la pagina y crear a otro admin.

Registrar admins siendo Super admin

---

app/controllers/groups_controller.rb
app/views/devise/registrations/new.html.erb
app/views/groups/show.html.erb
app/views/pages/index.html.erb
app/views/users/index.html.erb
app/views/users/show.html.erb

Adds buttons to have better navigation in the app

Adds buttons for navigation

---

db/seeds.rb

Changes seedof admin

---

app/views/admins/passwords/new.html.erb
app/views/admins/registrations/new.html.erb
app/views/admins/sessions/new.html.erb
app/views/devise/passwords/new.html.erb
app/views/devise/registrations/new.html.erb
app/views/devise/sessions/new.html.erb
app/views/groups/index.html.erb
app/views/groups/new.html.erb
app/views/groups/show.html.erb
app/views/groups_users/new.html.erb
app/views/layouts/_footer.html.erb
app/views/layouts/application.html.erb
app/views/pages/home.html.erb
app/views/pages/index.html.erb
app/views/users/index.html.erb
app/views/users/show.html.erb

Ivan, ahora los footers tambien aparecen cuando creas una nueva pagina

cambio footers

---

Deployment.md
app/controllers/groups_controller.rb
app/views/groups/new.html.erb
app/views/layouts/application.html.erb

Creation of deployment.md

---

app/assets/stylesheets/application.scss
app/views/devise/sessions/new.html.erb
app/views/pages/home.html.erb

Arreglar la imagen de fondo de la pantalla inicial y de la ruta /
Como se veia previamente:
Como se ve ahora:

Arreglar la imagen de fondo

---

Gemfile
Gemfile.lock
app/controllers/application_controller.rb
app/controllers/pages_controller.rb
app/controllers/students_controller.rb
app/controllers/users/registrations_controller.rb
app/models/user.rb
app/policies/application_policy.rb
app/policies/student_policy.rb
app/policies/user_policy.rb

- Adds Pundit gem to handle the authorization across different user roles.
- Implements authorization for Students, Users and Pages controller

Implements authorization

---

app/views/layouts/_navbar.html.erb
db/schema.rb

Navbar was using old routes which caused it to crash after login.

BUG002: Fix login crash

---

app/controllers/scholarships_controller.rb
app/helpers/scholarship_oportunities_helper.rb
app/models/scholarship_oportunity.rb
app/views/scholarship_oportunities/show.html.erb
app/views/scholarships/_form.html.erb

- Fixes importing students using an excel file.

Importing from excel is supported using new db schema

---

app/controllers/students_controller.rb
app/policies/student_policy.rb
app/views/devise/registrations/new_with_student.html.erb
app/views/students/_form_contact_information.html.erb
app/views/students/_student_info.html.erb
app/views/students/_students_table.html.erb
app/views/students/edit.html.erb
app/views/students/show.html.erb

Added contact information to update student info view. Students will also be able to access the view, but they will only be able to edit the contact information (basic information like name, curp, etc. is still only editable by admins).
Student View
Admin View

Task 5.2 Add edit contact information feature

---

app/controllers/students_controller.rb
app/models/contact_information.rb
app/views/layouts/_navbar.html.erb
app/views/students/_history_details.html.erb
app/views/students/_students_table.html.erb
app/views/students/history.html.erb

Task 7.2 Add view change history feature

---

app/models/curriculum.rb
app/models/student.rb
db/migrate/20200422164420_create_active_storage_tables.active_storage.rb
db/migrate/20200422165137_create_curriculums.rb
db/schema.rb
test/fixtures/curriculums.yml
test/models/curriculum_test.rb

Create the model for the Curriculum of a former student. Active Storage is also added to attach the profile picture of the former student.
There are still missing to add tables and references for the Education History, Work Experience, Areas of Expertise, Language Knowledge, Courses and Certifications, Abilities, and the PDF attachment of the resume.

Model for former student's Curriculum

---

app/models/user.rb
app/views/layouts/_header.html.erb
app/views/layouts/_navbar.html.erb

- Updates navbar and header to work with ex_student role.
- Add ex_student role to User model.

Ex-student role

---

app/models/curriculum.rb
app/models/education_history.rb
db/migrate/20200422203318_create_education_histories.rb
db/schema.rb
test/fixtures/education_histories.yml
test/models/education_history_test.rb

Add model to store the education history of a Former Student. Created with:
```
$ rails g model EducationHistory curriculum:references start_date:date end_date:date area_of_study:string university:string brief_description:string
```

Former student education

---

app/models/curriculum.rb
app/models/language.rb
db/migrate/20200422233417_create_languages.rb
db/schema.rb
test/fixtures/languages.yml
test/models/language_test.rb

Create Model to store de languages a former student knows as part of his curriculum.

Add Model for Languages

---

app/controllers/job_postings_controller.rb
app/models/job_posting.rb
app/views/job_postings/_form.html.erb
app/views/job_postings/_job_posting.json.jbuilder
app/views/job_postings/edit.html.erb
app/views/job_postings/index.html.erb
app/views/job_postings/index.json.jbuilder
app/views/job_postings/new.html.erb
app/views/job_postings/show.html.erb
app/views/job_postings/show.json.jbuilder
config/routes.rb
db/migrate/20200427200605_create_job_postings.rb
db/schema.rb
test/controllers/job_postings_controller_test.rb

- Adds JobPosting model, views and controller.

Adds JobPosting

---

app/assets/stylesheets/application.scss
app/views/job_postings/_form.html.erb
app/views/job_postings/edit.html.erb
app/views/job_postings/index.html.erb
app/views/job_postings/new.html.erb
app/views/job_postings/show.html.erb

- Adds styles for all views related to JobPosting model

Styles for JobPosting

---

app/helpers/application_helper.rb
app/models/user.rb
app/views/layouts/_header.html.erb
app/views/layouts/_navbar.html.erb
app/views/pages/home.html.erb

- Adds new company role.
- Updates view to work with company role

Company role

---

app/controllers/job_postings_controller.rb
app/policies/job_posting_policy.rb
app/views/pages/home.html.erb

- Adds policy for JobsPosting controller
- Fix issue that caused app to break when user was not logged in.

JobPosting policy

---

app/controllers/companies_controller.rb
app/helpers/companies_helper.rb
app/models/company.rb
app/models/user.rb
app/views/companies/_company.json.jbuilder
app/views/companies/_form.html.erb
app/views/companies/edit.html.erb
app/views/companies/index.html.erb
app/views/companies/index.json.jbuilder
app/views/companies/new.html.erb
app/views/companies/show.html.erb
app/views/companies/show.json.jbuilder
config/routes.rb
db/migrate/20200428182545_create_companies.rb
db/schema.rb
test/controllers/companies_controller_test.rb

- Adds Company scaffold
- Creates relationship between User and Company models.
Follow up PR will implement styles.

Company Model

---

app/assets/stylesheets/style.scss
app/controllers/companies_controller.rb
app/controllers/users/registrations_controller.rb
app/policies/user_policy.rb
app/views/companies/_company.json.jbuilder
app/views/companies/index.html.erb
app/views/companies/index.json.jbuilder
app/views/companies/new.html.erb
app/views/companies/show.json.jbuilder
app/views/devise/registrations/new_with_company.html.erb
config/routes.rb

- Creates new view to create a User of type company, including Company model fields.
- Styles Company creation and index.

Company styles

---

app/controllers/job_postings_controller.rb
app/models/company.rb
app/models/job_posting.rb
app/views/job_postings/_form.html.erb
db/migrate/20200428200605_create_job_postings.rb
db/schema.rb

- Adds one-to-many relationship for Company and JobPostings.
- Modifies existing creation view to work with this association.

Company-JobPosting relationship

---

app/views/students/_student_info.html.erb

- Validates that student has an scholarship associated to avoid nil exceptions.

Fix Student show

---

app/models/user.rb
app/policies/job_posting_policy.rb
app/views/job_postings/_form.html.erb

- Updates JobPostingPolicy to allow super admin users to create/update JobPostings.
- Updates new JobPosting views to allow selecting a Company to associate a given JobPosting.

Super admin JobPosting creation

---

app/controllers/companies_controller.rb
app/controllers/job_postings_controller.rb
app/policies/company_policy.rb
app/views/layouts/_navbar.html.erb

- Creates policy for Company.
- Updates Navbar to access JobPostings and Companies.

Company policies 

---

app/controllers/companies_controller.rb
app/models/company.rb
app/views/companies/_form.html.erb
app/views/companies/edit.html.erb
app/views/job_postings/index.html.erb
app/views/job_postings/show.html.erb

- Adds logo to Company model.
- Updates Company edit view to allow updaloading logo

Company Logo

---

app/models/student.rb
app/models/work_experience.rb
db/migrate/20200430002042_create_work_experiences.rb
db/schema.rb
test/fixtures/work_experiences.yml
test/models/work_experience_test.rb

Add work experience model with required fields.

Add work experience table

---

Gemfile
Gemfile.lock
app/assets/javascripts/application.js
app/assets/stylesheets/application.scss
app/controllers/curriculums_controller.rb
app/helpers/curriculums_helper.rb
app/models/curriculum.rb
app/models/student.rb
app/views/curriculums/_certification_fields.html.erb
app/views/curriculums/_education_history_fields.html.erb
app/views/curriculums/_form.html.erb
app/views/curriculums/_language_fields.html.erb
app/views/curriculums/edit.html.erb
app/views/curriculums/new.html.erb
app/views/curriculums/show.html.erb
app/views/students/_students_table.html.erb
app/views/students/history.html.erb
db/migrate/20200422165137_create_curriculums.rb
db/schema.rb

Create and design the Show and Edit view for the Curriculum of a student.
Added cocoon gem to make it simpler to have repeated nested attributes.
Also fixed a typo in the migrations.

Create and Design the Show and Edit views for Curriculum

---

app/controllers/users/registrations_controller.rb
app/policies/user_policy.rb
app/views/devise/registrations/new_with_former_student.html.erb
app/views/layouts/_navbar.html.erb
config/routes.rb

Add `new_with_former_student` view so that the admin can create a former student. The functionality to bulk upload former students is not yet implemented.

Add a view to create a Former Student

---

app/assets/stylesheets/application.scss
app/controllers/curriculums_controller.rb
app/models/curriculum.rb
app/models/student.rb
app/models/work_experience.rb
app/views/curriculums/_form.html.erb
app/views/curriculums/_work_experience_fields.html.erb
app/views/curriculums/show.html.erb
db/migrate/20200430190242_edit_work_experiences.rb
db/schema.rb

Update work experience to belong to curriculum instead of user.
Add feature to add/edit work experience in curriculum.

Add work experience view

---

app/controllers/curriculums_controller.rb
app/helpers/application_helper.rb
app/models/curriculum.rb
app/views/curriculums/_form.html.erb
app/views/curriculums/show.html.erb
app/views/layouts/_navbar.html.erb

- Add feature to upload/update curriculum
- Update curriculum show view
- UI fixes

Add upload curriculum feature

---

app/controllers/curriculums_controller.rb
app/views/curriculums/_form.html.erb
app/views/curriculums/_work_experience_fields.html.erb
app/views/curriculums/show.html.erb
db/migrate/20200504223008_add_current_job.rb
db/schema.rb
public/javascript/curriculum.js

Add option to have work experience as current job in curriculum.

Add current job

---

app/controllers/job_postings_controller.rb
app/models/job_posting.rb
app/views/job_postings/_form.html.erb
db/migrate/20200428200605_create_job_postings.rb
db/schema.rb

- Adds expiration_date column to JobPosting model.
- Updates JobPosting controller and views to work with expiration_date field.

Add expiration_date to JobPostings

---

Gemfile
Gemfile.lock
app/assets/javascripts/application.js
app/controllers/job_postings_controller.rb
app/models/job_posting.rb
app/views/job_postings/_list.html.erb
app/views/job_postings/index.html.erb
app/views/job_postings/index.js

- Adds filterrific gem to handle JobPosting filtering feature.
- Adds basic filter by JobPosting title.

Implements basics filtering by job posting title

---

app/controllers/students_controller.rb
app/models/curriculum.rb
app/models/user.rb
app/views/students/_former_students_table.html.erb
app/views/students/_student_info.html.erb

Allow the admin to download all data of former students into a CSV in order to filter and manipulate the data in excel.

Allow download of former students

---

app/assets/stylesheets/application.scss
app/controllers/job_postings_controller.rb
app/models/company.rb
app/models/job_posting.rb
app/views/job_postings/index.html.erb

- Implements JobPosting filtering by company_id.
- Enhances filter UI.

Company name filter

---

app/views/curriculums/_form.html.erb
app/views/job_postings/_list.html.erb
app/views/job_postings/index.html.erb
app/views/job_postings/show.html.erb

Fix bugs regarding to job postings that were causing the app to crash.

Fix bugs regarding to job postings

---

app/controllers/job_postings_controller.rb
app/models/job_posting.rb
app/views/job_postings/index.html.erb

- Adds keyword filtering feature for JobPosting index.

Keyword filtering

---

Gemfile
Gemfile.lock
app/controllers/application_controller.rb
app/controllers/job_postings_controller.rb
app/models/job_posting.rb
app/views/job_postings/index.html.erb

- Adds pagination to JobPosting index view.
- Adds custom renderer to handle ui for pagination buttons and pages.

JobPosting pagination

---

app/controllers/job_applications_controller.rb
app/helpers/job_applications_helper.rb
app/models/job_application.rb
app/models/job_posting.rb
app/models/student.rb
app/views/job_applications/_form.html.erb
app/views/job_applications/_job_application.json.jbuilder
app/views/job_applications/edit.html.erb
app/views/job_applications/index.html.erb
app/views/job_applications/index.json.jbuilder
app/views/job_applications/new.html.erb
app/views/job_applications/show.html.erb
app/views/job_applications/show.json.jbuilder
config/routes.rb
db/migrate/20200521152231_create_job_applications.rb
db/schema.rb
test/controllers/job_applications_controller_test.rb

- Adds new JobApplication join table.
- Adds scaffold for JobApplication
- Follow up Pr will implement styles and policies.

JobApplications

---

app/controllers/students_controller.rb
app/models/student.rb
app/models/unemployment_datum.rb
app/views/students/first_time_login.html.erb
db/migrate/20200521162746_create_unemployment_data.rb
db/migrate/20200521163747_create_unemployment_data.rb
db/schema.rb
test/fixtures/unemployment_data.yml
test/models/unemployment_datum_test.rb

Create the model to store the unemployment data and add the fields to the first_time_login view. The model was created using:
```
rails g model UnemploymentData is_employed:boolean unemployment_reason:text student:references
```

Former student unemployment

---

app/models/user.rb

Add unemployment data to the former students csv.

Add unemployment data to the former students csv

---

app/assets/stylesheets/application.scss
app/views/curriculums/_certification_fields.html.erb
app/views/curriculums/_education_history_fields.html.erb
app/views/curriculums/_form.html.erb
app/views/curriculums/_language_fields.html.erb
app/views/curriculums/_work_experience_fields.html.erb
app/views/curriculums/edit.html.erb
app/views/curriculums/new.html.erb
app/views/curriculums/show.html.erb
app/views/devise/registrations/new_with_company.html.erb
app/views/devise/registrations/new_with_former_student.html.erb
app/views/devise/registrations/new_with_student.html.erb
app/views/students/first_time_login.html.erb
db/schema.rb

- Standardize CV views
- Random UI fixes

Standardize CV views

---

app/controllers/students_controller.rb
app/helpers/application_helper.rb
app/models/company.rb
app/models/student.rb
app/models/user.rb
app/policies/company_policy.rb
app/policies/curriculum_policy.rb
app/policies/job_posting_policy.rb
app/policies/student_policy.rb
app/views/curriculums/show.html.erb
app/views/layouts/_navbar.html.erb
app/views/students/_former_students_table.html.erb
app/views/students/history.html.erb
app/views/students/show.html.erb

Fix some minor bugs:
- Redirect correctly when deleting a user
- Add the country of birth to the user when uploading a file
- Cascade deletion of relations
- Add more exhaustive checks to policies to avoid checking on Nil objects
- Modify the back button behaviour by actually going to the previous page (For example when checking candidates of job posting the back button did not behave correctly)
- Remove links to student/show and student/history in the candidates view for non admin roles

Fix minor bugs

---

app/views/curriculums/show.html.erb
app/views/devise/registrations/new.html.erb
app/views/devise/registrations/new_with_company.html.erb
app/views/devise/registrations/new_with_former_student.html.erb
app/views/devise/registrations/new_with_student.html.erb
app/views/job_postings/_form.html.erb
app/views/job_postings/_list.html.erb
app/views/job_postings/candidates.html.erb
app/views/job_postings/edit.html.erb
app/views/job_postings/index.html.erb
app/views/job_postings/new.html.erb
app/views/job_postings/show.html.erb
app/views/pages/dashboard.html.erb
app/views/scholarship_oportunities/new.html.erb
app/views/students/_former_students_table.html.erb
app/views/students/history.html.erb
app/views/students/show.html.erb

- Update job posting UI to match other views

Update job postings UI

---

app/assets/javascripts/curriculum.js
config/environments/production.rb

Some other errors that were present when doing the deployment. The configuration of the project does not support ES6

Fix js compile errors

---

app/views/devise/sessions/new.html.erb
app/views/layouts/_alerts.html.erb

Adds errors as materialize toasts

---

app/controllers/scholarships_controller.rb
app/helpers/application_helper.rb

Add error handling to excel upload

---

Gemfile
Gemfile.lock
app/assets/javascripts/curriculum.js
app/helpers/application_helper.rb
app/views/curriculums/_work_experience_fields.html.erb
app/views/students/_form.html.erb
app/views/students/_form_contact_information.html.erb

State and Country Dropdowns

---

app/views/devise/registrations/edit.html.erb
app/views/devise/registrations/new_with_former_student.html.erb
app/views/devise/shared/_error_messages.html.erb
app/views/layouts/_header.html.erb

Add view to change password and a button in the header to get to it.

Add view to change password

---

app/views/curriculums/_certification_fields.html.erb
app/views/curriculums/_education_history_fields.html.erb

Fix date columns

---

app/assets/stylesheets/application.scss
app/views/curriculums/_education_history_fields.html.erb
app/views/curriculums/_work_experience_fields.html.erb
app/views/devise/registrations/edit.html.erb
app/views/students/_form.html.erb
app/views/students/_history_details.html.erb
app/views/students/_students_table.html.erb
config/application.rb

Fix final ui bugs

---

app/views/devise/passwords/new.html.erb

Update lost password UI

---

app/views/job_postings/index.html.erb

1 am bug fix
